### ISSUE TITLE
#make the website available in multiple languages thus by improving its accessibility.

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ankit071105/Ticket-Booking#46] opened 2024-10-02 12:59 UTC
create a working dropdown with various languages spoken in different regions.

**Comment by ankit071105** [comment] 2024-10-02 13:03
> create a working dropdown with various languages spoken in different regions.

okay work like that if user changes the languages then whole website languages get changed @SanikaBhalerao1345  if you have solution i will assign this to you

**Comment by SanikaBhalerao1345** [comment] 2024-10-02 13:49
Hi @ankit071105 , yes I would like to work on this issue.

**Comment by ankit071105** [comment] 2024-10-02 13:56
> Hi @ankit071105 , yes I would like to work on this issue.

okay i am assiging this to you

**Comment by SumitSahu44** [comment] 2024-10-04 16:51
hey assign this to me i will make your website in different language under gssoc-ext label

**Comment by ankit071105** [comment] 2024-10-05 03:28
> hey assign this to me i will make your website in different language under gssoc-ext label

The issue is when user changes the languages then whole website languages get changed . if can this i will assign this to you . @SumitSahu44

**Comment by SumitSahu44** [comment] 2024-10-05 11:55
hey @ankit071105 I'm raady to do this in a single click we can change english to hindi language we have 2 options 
1- As per your current structure we can do this usinh HTML CSS and JS
2- Using reactjs so suggest me what tech stack i use to do this

**Comment by ankit071105** [comment] 2024-10-05 11:59
> hey @ankit071105 I'm raady to do this in a single click we can change english to hindi language we have 2 options 1- As per your current structure we can do this usinh HTML CSS and JS 2- Using reactjs so suggest me what tech stack i use to do this

current one only

**Comment by SumitSahu44** [comment] 2024-10-05 14:07
ok assign this to me i will build it and also add all labels

**Comment by SumitSahu44** [comment] 2024-10-06 05:15
hey @ankit071105 assign this to me with all labels i will do it

**Comment by SanikaBhalerao1345** [comment] 2024-10-13 07:05
hi @ankit071105 can i still raise PR?

**Closed** 2024-10-25 16:38 UTC
Labels: level2, gssoc-ext, hacktoberfest-accepted
